logging:
  level:
    "com.waveinformatica.demo": DEBUG

server:
  port: 8080
  error:
    include-message: always

demo:
  rest:
    markets:
      limit: 3000
  gruppo:
    esempio: pippo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mypass
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 9090

demo:
  gruppo:
    esempio: pluto
    s: ${DB_PASSWD}

  job:
    period: 60000